version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
  - package-ecosystem: npm
    directory: "/website"
    schedule:
      interval: daily
      time: "04:00"
